spring:
  application:
    name: Notification-Service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.ToStringSerializer;
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: orderCreatedEvent:com.olivedevs.notificationservice.event.OrderCreatedEvent


server:
  port: 8083